language: python
python:
  - "3.6"
install:
  - pip install pipenv
  - pipenv install --system --dev
  - pip install coveralls
env:
  global:
    - SECRET_KEY=SK
    - DJANGO_SETTINGS_MODULE=bothub.settings
    - SUPPORTED_LANGUAGES="en|pt"
    - DOCKER_IMAGE_NAME=ilha/bothub-nlp
    - SEND_EMAILS=false
before_script:
  - django-admin migrate
  - python download_spacy_models.py
script:
  - flake8
  - travis_wait coverage run -m unittest
after_success:
  - coveralls
  - export TAG=`if [ "${TRAVIS_BRANCH}" == "master" ]; then echo "latest"; else echo ${TRAVIS_BRANCH}; fi`
  - if [[ ${TRAVIS_EVENT_TYPE} == "push" && (${TRAVIS_BRANCH} == "master" || ${TRAVIS_BRANCH} == "develop") ]]; then export BUILD_DOCKER_IMAGES=true; fi
  - if [[ ${BUILD_DOCKER_IMAGES} ]]; then docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASS}; fi
  - if [[ ${BUILD_DOCKER_IMAGES} ]]; then travis_wait 40 ./build-flavors.sh; fi
  - if [[ ${BUILD_DOCKER_IMAGES} ]]; then docker push ${DOCKER_IMAGE_NAME}:${TAG}; fi
  - if [[ ${BUILD_DOCKER_IMAGES} ]]; then docker push ${DOCKER_IMAGE_NAME}:${TAG}-all; fi
  - if [[ ${BUILD_DOCKER_IMAGES} ]]; then docker push ${DOCKER_IMAGE_NAME}:${TAG}-all-vectorized; fi
