language: python
python:
  - "3.6"
install:
  - pip install pipenv
  - pipenv install --system
  - pip install coverage
  - pip install flake8
  - pip install coveralls
env:
  global:
    - SECRET_KEY=SK
    - DJANGO_SETTINGS_MODULE=bothub.settings
before_script:
  - DJANGO_SETTINGS_MODULE="${DJANGO_SETTINGS_MODULE}" django-admin migrate
script:
  - flake8
  - travis_wait coverage run -m unittest && coverage report -m
after_success:
  - coveralls
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - '[[ $TRAVIS_EVENT_TYPE == "push" && $TRAVIS_BRANCH == "master" || $TRAVIS_EVENT_TYPE == "push" && $TRAVIS_BRANCH == "develop" ]] && docker login -u "${DOCKER_HUB_USER}" -p "${$DOCKER_HUB_PASS}" && docker-compose -f docker/docker-compose.yml build bothub-nlp && docker push "${$DOCKER_IMAGE_NAME}":"${$TAG}"'
