language: python
python:
  - "3.6"
install:
  - pip install pipenv
  - pipenv install --system
  - pip install flake8
  - pip install coveralls
env:
  global:
    - SECRET_KEY=SK
    - SUPPORTED_LANGUAGES=en
    - EXTRA_LANGUAGE_MODELS_REPOSITORY=https://github.com/push-flow/spacy-lang-models.git
    - EXTRA_LANGUAGE_MODELS_REPOSITORY_DIR=./extra-models/
    - EXTRA_LANGUAGE_MODELS_DIR=./extra-models/models/
    - DJANGO_SETTINGS_MODULE=bothub.settings
before_script:
  - git clone --depth 1 --single-branch "${EXTRA_LANGUAGE_MODELS_REPOSITORY}" "${EXTRA_LANGUAGE_MODELS_REPOSITORY_DIR}"
  - python -m bothub_nlp import_supported_languages -e="${EXTRA_LANGUAGE_MODELS_DIR}"
  - DJANGO_SETTINGS_MODULE="${DJANGO_SETTINGS_MODULE}" django-admin migrate
script:
 - flake8 --exclude ./extra-models/
 - travis_wait coverage run -m unittest && coverage report -m
after_success:
  - coveralls
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - '[[ $TRAVIS_EVENT_TYPE == "push" && $TRAVIS_BRANCH == "master" || $TRAVIS_EVENT_TYPE == "push" && $TRAVIS_BRANCH == "develop" ]] && docker login -u "${DOCKER_HUB_USER}" -p "${$DOCKER_HUB_PASS}" && docker-compose -f docker/docker-compose.yml build bothub-nlp && docker push "${$DOCKER_IMAGE_NAME}":"${$TAG}"'
