sudo: required

language: python
python:
  - "3.6.2"

addons:
  apt:
    packages:
      - postgresql-9.4-postgis-2.3
      - python3
      - python3-pip
  postgresql: "9.4"

services:
  - redis-server

install:
  # install all Python dependencies
  - pip install --upgrade pip
  - pip --version
  - pip install -r requirements.txt --upgrade
  - pip install coveralls

before_script:
  # setup test database
  - psql -U postgres -c "CREATE USER buthub WITH PASSWORD 'bothub';"
  - psql -U postgres -c "ALTER ROLE buthub WITH SUPERUSER;"
  - psql -U bothub postgres -c "CREATE DATABASE bothub;"
  - cd app/models
  - export BOTHUB_POSTGRES_USER=bothub
  - export BOTHUB_POSTGRES_PASSWORD=botuhb
  - export BOTHUB_POSTGRES_DB=bothub
  - export BOTHUB_POSTGRES=127.0.0.1
  - export BOTHUB_POSTGRES_PORT=5432
  - export BOTHUB_REDIS=127.0.0.1
  - export BOTHUB_REDIS_PORT=6379
  - export BOTHUB_REDIS_DB=2
  - python create_schema.py 
  - cd ..

script:
 - cd app
 - coverage run -m unittest tests

after_success:
  - coveralls --rcfile ../.coveragerc
  - coverage report -i --rcfile ../.coveragerc  --fail-under=90