version: '3.3'

services:
  scipy:
    image: ilha/scipy:python3.6-alpine3.7
    build:
      context: ./scipy
      dockerfile: Dockerfile
  bothub-nlp:
    image: ${DOCKER_IMAGE_NAME:-ilha/bothub-nlp}:${TAG:-latest}
    build:
      context: ..
      dockerfile: docker/bothub-nlp/Dockerfile
    ports:
      - 80:80
    environment:
      - SECRET_KEY
      - DEBUG
      - ALLOWED_HOSTS
      - DEFAULT_DATABASE
      - LANGUAGE_CODE
      - TIME_ZONE
      - ADMINS
      - DEFAULT_FROM_EMAIL
      - SERVER_EMAIL
      - EMAIL_HOST
      - EMAIL_PORT
      - EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD
      - EMAIL_USE_SSL
      - EMAIL_USE_TLS
      - BOTHUB_WEBAPP_BASE_URL
      - BOTHUB_NLP_BASE_URL
      - SUPPORTED_LANGUAGES
      - SPACY_LANG_MODELS_REPOSITORY
